BUCKET_NAME = "seabot-d2-storage"
S3_MODEL_ROOT_PATH = "SeaBot/Models"
WANDB_KEY = "856878a46a17646e66281426d43c4b77d3f9a00c"
MODEL_ROOT_PATH = "local_models"
OLD_MODEL_PATH = "SeaBot/Models/best_model_swin.pth"
OLD_MODEL_NAME = "best_model_swin.pth"
FATHOMNET_RELATIVE_PATH = "fathomnet"
S3_MODEL_PATH = "SeaBot/Models/fn_final_trained_model_pretrained.pth"
LOCAL_MODEL_PATH = "fn_final_trained_model_pretrained.pth"

NUM_EPOCHS = 1
PATIENCE = 1
SAVE_FREQ = 100000
LOCAL_MODEL_DIR = "local_models"
LOCAL_VIDEO_DIR = "local_videos"
LOCAL_IMAGE_DIR = "local_images"
DATASET_ROOT_PATH = "SeaBot/Data/EX2304_Compressed"
IMAGE_ROOT_PATH = "SeaBot/Data/Extracted_Images"
TRAINING_MODEL_ROOT_PATH = "SeaBot/Models"

MODEL_NAME = "microsoft/beit-large-patch16-224"
# swin_large_patch4_window7_224, large_EX2304_1_vit, microsoft/beit-large-patch16-224
